blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm
app_name = "blog"

urlpatterns = [
    path('', views.index, name="index"),
    path('posts/', views.post_list, name="post_list"),
    path('posts/<str:category>', views.post_list, name="post_list_category"),
    # path('posts/', views.PostListView.as_view(), name="post_list"),
    # path('posts/<int:id>', views.post_detail, name="post_detail"),
    path('posts/detail/<pk>', views.post_detail, name="post_detail"),
    path('posts/<post_id>/comment', views.post_comment, name="post_comment"),
    path('ticket', views.ticket, name="ticket"),
    path('search/', views.post_search, name="post_search"),
    path('profile/', views.profile, name="profile"),
    path('profile/create_post', views.create_post, name="create_post"),
    path('profile/create_post/<post_id>', views.edit_post, name="edit_post"),
    path('profile/delete_post/<post_id>', views.delete_post, name="delete_post"),
    path('profile/delete_image/<image_id>', views.delete_image, name="delete_image"),
    # path('login/', views.login,name="login"),
    path('login/', auth_views.LoginView.as_view(authentication_form=LoginForm), name="login"),
    # path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('logout/', views.log_out, name="logout"),

    path('password-change/', auth_views.PasswordChangeView.as_view(success_url='done'), name="password_change"),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),

    path('password-reset/', auth_views.PasswordResetView.as_view(success_url='done'), name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url='/blog/password-reset/complete'), name="password_reset_confirm"),
    path('password-reset/complete/',auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),

    path('register/', views.register, name="register"),
    path('account/edit', views.edit_account, name="edit_account"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include("blog.urls", namespace="blog")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/forms.py
from cProfile import label

from django import forms
from .models import Comment, Post, User, Account
from django.contrib.auth.forms import AuthenticationForm

class TicketForm(forms.Form):
    SUBJECT_CHOICES = (
        ('پیشنهاد', 'پیشنهاد'),
        ('انتقاد', 'انتقاد'),
        ('گزارش', 'گزارش'),
    )
    message = forms.CharField(widget=forms.Textarea, required=True)
    name = forms.CharField(max_length=250, required=True)
    email = forms.EmailField()
    phone = forms.CharField(max_length=11, required=True)
    subject = forms.ChoiceField(choices=SUBJECT_CHOICES)

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if phone:
            if not phone.isnumeric():
                raise forms.ValidationError("شماره تلفن عددی نیست!")
            else:
                return phone


class CommentForm(forms.ModelForm):
    def clean_name(self):
        name = self.cleaned_data['name']
        if name:
            if len(name) < 3:
                raise forms.ValidationError("نام کوتاه است")
            else:
                return name

    class Meta:
        model = Comment
        fields = ['name', 'body']
        widgets={
            'body': forms.TextInput(attrs={
                'placeholder': 'متن',
                'class':'form-control'
            }),
            'name': forms.TextInput(attrs={
                'placeholder': 'نام',
                'class': 'form-control'
            }),
        }

class SearchForm(forms.Form):
    query = forms.CharField()

class CreatePostForm(forms.ModelForm):
    image1 = forms.ImageField(label="تصویر اول", widget=forms.FileInput(attrs={'class': 'form-control'}))
    image2 = forms.ImageField(label="تصویر دوم", widget=forms.FileInput(attrs={'class': 'form-control'}))
    class Meta:
        model = Post
        fields = ['title', 'description', 'reading_time', 'category']
        widgets={
            'title': forms.TextInput(attrs={
                'class':'form-control',
                'id' : "con-name",

            }),
            'description': forms.Textarea(attrs={
            	'class': 'form-control',
				 'rows': '5',
            }),
            'reading_time': forms.NumberInput(attrs={
                'class': 'form-control',
            }),
            'category': forms.Select(attrs={
                'class': 'form-select',
            }),


        }


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=250, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(max_length=250, required=True, widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(max_length=20, widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='پسورد')
    password2 = forms.CharField(max_length=20, widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='تکرار پسورد')
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name' , 'email']
        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'form-control',

            }),
            'first_name': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'last_name': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
            }),
        }
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('پسورد ها مطابقت ندارند!')
        return cd['password2']

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']
        widgets = {
            'first_name': forms.TextInput(attrs={
                'class': 'form-control',

            }),
            'last_name': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
            }),
        }

class AccountEditForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['date_of_birth', 'bio', 'job', 'photo']
        widgets = {
            'date_of_birth': forms.DateInput(attrs={
                'class': 'form-control',
            }),
            'bio': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': '5',
            }),
            'job': forms.TextInput(attrs={
                'class': 'form-control',

            }),
            'photo': forms.FileInput(attrs={
                'class': 'form-control',
            }),
        }

blog/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from .models import *
from .forms import *
# from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView
from django.views.decorators.http import require_POST
from django.db.models import Q
from django.contrib.postgres.search import TrigramSimilarity
from django.contrib.auth import authenticate, login, logout
# Create your views here.
from django.contrib.auth.decorators import login_required

def index(request):
    last_post = Post.published.all().order_by('-publish')[0]
    return render(request, "blog/index.html", {"last_post": last_post})


def post_list(request, category=None):
    if category is not None:
        posts = Post.published.filter(category=category)
    else:
        posts = Post.published.all()
    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)
    print(posts, type(posts))
    context = {
        'posts': posts,
        'category': category
    }
    return render(request, "blog/list.html", context)

# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = "posts"
#     paginate_by = 4f
#     template_name = "blog/list.html"


def post_detail(request, pk):
    post = get_object_or_404(Post, id=pk, status=Post.Status.PUBLISHED)
    comments = post.comments.filter(active=True)
    form = CommentForm()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, "blog/detail.html", context)


# class PostDetailView(DetailView):
#     model = Post
#     template_name = "blog/detail.html"


def ticket(request):
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            Ticket.objects.create(message=cd['message'], name=cd['name'], email=cd['email'],
                                  phone=cd['phone'], subject=cd['subject'])
            return redirect("blog:index")
    else:
        form = TicketForm()
    return render(request, "forms/ticket.html", {'form': form})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    context = {
        'post': post,
        'form': form,
        'comment': comment
    }
    return render(request, "forms/comment.html", context)


def post_search(request):
    query=None
    results=[]
    if 'query' in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query=form.cleaned_data['query']
            results1=Post.published.annotate(similarity=TrigramSimilarity('title', query))\
                .filter(similarity__gt=0.1)
            results2 = Post.published.annotate(similarity=TrigramSimilarity('description', query)) \
                .filter(similarity__gt=0.1)
            results = (results1 | results2).order_by('-similarity')
    context={
        'query':query,
        'results':results
    }
    return render(request,'blog/search.html',context)

@login_required
def profile(request):
    user = request.user
    posts= Post.published.filter(author=user)

    return render(request, 'blog/profile.html', {'posts':posts})

@login_required
def create_post(request):
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_file=form.cleaned_data['image1'], post= post)
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            return redirect('blog:profile')
    else:
        form = CreatePostForm()
    return render(request, 'forms/create-post.html', {'form': form})

@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        post.delete()
        return redirect('blog:profile')
    return render(request, 'forms/delete-post.html', {'post': post})

@login_required
def delete_image(request, image_id):
    image = get_object_or_404(Image, id=image_id)
    image.delete()
    return redirect('blog:profile')

@login_required
def edit_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_file=form.cleaned_data['image1'], post=post)
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            return redirect('blog:profile')
    else:
        form = CreatePostForm(instance=post)
    return render(request, 'forms/create-post.html', {'form': form, 'post': post})

# def user_login(request):
#     if request.method == "POST":
#         form = LoginForm(request.POST)
#         if form.is_valid():
#             cd = form.cleaned_data
#             user = authenticate(request, username=cd['username'], password=cd['password'])
#             if user is not None:
#                 if user.is_active:
#                     login(request, user)
#                     return redirect('blog:profile')
#                 else:
#                     return HttpResponse('Your account is disabled')
#             else:
#                 return HttpResponse('You are not logged in')
#
#     else:
#         form = LoginForm()
#     return render(request, 'forms/login.html', {'form': form})

def log_out(request):
    logout(request)
    return redirect(request.META.get('HTTP_REFERER'))


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            Account.objects.create(user=user)
            return  render(request, 'registration/register_done.html', {'user': user})
    else:
        form = UserRegisterForm()
    return render(request, 'registration/register.html', {'form': form})


@login_required
def edit_account(request):
    if request.method == 'POST':
        user_form = UserEditForm(request.POST, instance=request.user)
        account_form = AccountEditForm(request.POST, instance=request.user.account, files=request.FILES)
        if account_form.is_valid() and user_form.is_valid():
            account_form.save()
            user_form.save()
    else:
        user_form = UserEditForm(instance=request.user)
        account_form = AccountEditForm(instance=request.user.account)
    context ={
        'account_form': account_form,
        'user_form': user_form
    }
    return render(request, 'registration/edit_account.html', context)

blog/templates/forms/comment.html
{% extends 'parent/base.html' %}
{% load jformat %}
{% load static %}
{% block title %}post comment{% endblock %}

{% block content %}

    {% if comment %}
      <div class="centered mb-4 text-center">
        <h2 class="h1 m-0">کامنت شما ثبت شد.</h2>
          <br>
      <a href="{{ post.get_absolute_url }}" class="btn btn-dark mb-0"> بازگشت به پست</a>
      </div>

    {% else %}
    <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="افزودن کامنت">
    </form>
    {% endif %}


        <!-- Bootstrap JS -->
<script src="{% static 'vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>

<!-- Template Functions -->
<script src="{% static 'js/functions.js' %}"></script>
{% endblock %}

blog/templates/forms/create-post.html
{% extends 'parent/base.html' %}
{% block title %}profile{% endblock %}
{% block content %}

<section class="py-4">
	<div class="container">
    <div class="row pb-4">
			<div class="col-12">
        <!-- Title -->
        <h1 class="mb-0 h3">ایجاد یا ویرایش پست</h1>
			</div>
		</div>
		<div class="row">
			<div class="col-12">
				<!-- Chart START -->
				<div class="card border h-100">
					<!-- Card body -->
					<div class="card-body">
            <!-- Form START -->

<form method="post" enctype="multipart/form-data">
<div class="row">
    <div class="col-12">
    {% csrf_token %}

	{{ form.as_p }}
    {% if post %}
        {% for img in post.images.all %}
        <div class="row align-items-center mb-2">
          <div class="col-4 col-md-2">
                <div class="position-relative">
                  <img class="rounded mb-3" src="{{ img.image_file.url }}" alt="">
                      <div class="position-absolute top-0 end-0 mt-n2 me-n2">
                        <a class="btn btn-icon btn-xs btn-danger" href="{% url 'blog:delete_image' img.id %}"><i class="bi bi-x"></i></a>
                      </div>
            </div>
          </div>
        {% endfor %}
    {% endif %}
    </div>
</div>
<button class="btn btn-primary" type="submit">ذخیره</button>
</div>
</form>

                    <!-- Form END -->
        </div>
    </div><!-- Chart END -->
</div>
    </div>
	</div>
</section>



    <script src="assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

<!-- Vendors -->
<script src="assets/vendor/apexcharts/js/apexcharts.min.js"></script>
<script src="assets/vendor/quill/js/quill.min.js"></script>

<!-- Template Functions -->
<script src="assets/js/functions.js"></script>
<!-- Btn Upload -->
<script>
   document.querySelector(".upload-button").addEventListener("click", () => {
	  //clicks on the file input
	  document.querySelector(".hidden-upload").click();
	});
	//adds event listener on the hidden file input to listen for any changes
	document.querySelector(".hidden-upload").addEventListener("change", (event) => {
	  //gets the file name
	  document.querySelector(".upload-name").value = event.target.files[0].name;
	});
</script>

{% endblock %}

blog/templates/forms/delete-post.html
{% extends 'parent/base.html' %}
{% load jformat %}
{% block title %}post delete{% endblock %}

{% block content %}
      <div class="centered mb-4 text-center">
    <h2 class="h1 m-0"> آیا از حذف پست ({{ post.title }})  مطمعن هستید؟ </h2>
      <br>
  		<a href="{% url 'blog:profile' %}" class="btn btn-dark mb-0"> برگشت به صفحه پروفایل</a>
  </div>
    <br>
    <form method="post">
        {% csrf_token %}
        <div class="centered mb-4 text-center">
        <button class="btn btn-primary center" type="submit">حذف</button>
        </div>

    </form>
{% endblock %}

blog/templates/forms/ticket.html
{% extends 'parent/base.html' %}
{% block title %}ticket form{% endblock %}
{% block content %}
<section class="py-4">
	<div class="container">
    <div class="row pb-4">
			<div class="col-12">
        <!-- Title -->
        <h1 class="mb-0 h3">ارسال تیکت به پشتیبانی</h1>
			</div>
		</div>
		<div class="row">
			<div class="col-12">
				<!-- Chart START -->
				<div class="card border h-100">
					<!-- Card body -->
					<div class="card-body">
            <!-- Form START -->

    <form method="post">
    {% csrf_token %}
        نام و نام خانوادگی:
    <input type="text" name="name" required class="form-control" placeholder=""
            {% if form.name.value %} value="{{ form.name.value }}" {% endif %}>

        <br>
        ایمیل:
    <input type="email" name="email" class="form-control" placeholder
            {% if form.email.value %} value="{{ form.email.value }}" {% endif %} >

        <br>
        شماره تماس:
    <input type="text" name="phone" required maxlength="11" class="form-control"
    {% if form.phone.value %} value="{{ form.phone.value }}" {% endif %}>
        <br>
        متن:
    <textarea class="form-control" rows="3" name="message">{% if form.message.value %}{{ form.message.value }}{% endif %}</textarea>
        <br>

    <select name="subject" class="form-select">
        <option value="پیشنهاد"
                {% if form.subject.value == 'پیشنهاد' %} selected {% endif %}>
            پیشنهادات</option>
        <option value="انتقاد"
        {% if form.subject.value == 'انتقاد' %} selected {% endif %}>
            انتقادات</option>
        <option value="گزارش"
                {% if form.subject.value == 'گزارش' %} selected {% endif %}>
            گزارش</option>
    </select>
        <br>
    <button class="btn btn-primary" type="submit">ارسال تیکت</button>
    </form>
                    <!-- Form END -->
        </div>
    </div><!-- Chart END -->
</div>
    </div>
	</div>
</section>
    {% if form.errors %}
        لطفا خطاهای زیر را اصلاح کنید!
        <br>
        {% for field in form %}
            {% if field.errors %}
                {% for error in field.errors %}
                    {{ field.label }} : {{ error }}
                {% endfor %}
            {% endif %}
        {% endfor %}
    {% endif %}

    {%  if form.non_field_errors %}
        {{ form.non_field_errors }}
    {% endif %}
{% endblock %}