blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm
app_name = "blog"

urlpatterns = [
    path('', views.index, name="index"),
    path('posts/', views.post_list, name="post_list"),
    path('posts/<str:category>', views.post_list, name="post_list_category"),
    # path('posts/', views.PostListView.as_view(), name="post_list"),
    # path('posts/<int:id>', views.post_detail, name="post_detail"),
    path('posts/detail/<pk>', views.post_detail, name="post_detail"),
    path('posts/<post_id>/comment', views.post_comment, name="post_comment"),
    path('ticket', views.ticket, name="ticket"),
    path('search/', views.post_search, name="post_search"),
    path('profile/', views.profile, name="profile"),
    path('profile/create_post', views.create_post, name="create_post"),
    path('profile/create_post/<post_id>', views.edit_post, name="edit_post"),
    path('profile/delete_post/<post_id>', views.delete_post, name="delete_post"),
    path('profile/delete_image/<image_id>', views.delete_image, name="delete_image"),
    # path('login/', views.login,name="login"),
    path('login/', auth_views.LoginView.as_view(authentication_form=LoginForm), name="login"),
    # path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('logout/', views.log_out, name="logout"),

    path('password-change/', auth_views.PasswordChangeView.as_view(success_url='done'), name="password_change"),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),

    path('password-reset/', auth_views.PasswordResetView.as_view(success_url='done'), name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url='/blog/password-reset/complete'), name="password_reset_confirm"),
    path('password-reset/complete/',auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),

    path('register/', views.register, name="register"),
    path('account/edit', views.edit_account, name="edit_account"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include("blog.urls", namespace="blog")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/forms.py
from cProfile import label

from django import forms
from .models import Comment, Post, User, Account
from django.contrib.auth.forms import AuthenticationForm

class TicketForm(forms.Form):
    SUBJECT_CHOICES = (
        ('پیشنهاد', 'پیشنهاد'),
        ('انتقاد', 'انتقاد'),
        ('گزارش', 'گزارش'),
    )
    message = forms.CharField(widget=forms.Textarea, required=True)
    name = forms.CharField(max_length=250, required=True)
    email = forms.EmailField()
    phone = forms.CharField(max_length=11, required=True)
    subject = forms.ChoiceField(choices=SUBJECT_CHOICES)

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if phone:
            if not phone.isnumeric():
                raise forms.ValidationError("شماره تلفن عددی نیست!")
            else:
                return phone


class CommentForm(forms.ModelForm):
    def clean_name(self):
        name = self.cleaned_data['name']
        if name:
            if len(name) < 3:
                raise forms.ValidationError("نام کوتاه است")
            else:
                return name

    class Meta:
        model = Comment
        fields = ['name', 'body']
        widgets={
            'body': forms.TextInput(attrs={
                'placeholder': 'متن',
                'class':'form-control'
            }),
            'name': forms.TextInput(attrs={
                'placeholder': 'نام',
                'class': 'form-control'
            }),
        }

class SearchForm(forms.Form):
    query = forms.CharField()

class CreatePostForm(forms.ModelForm):
    image1 = forms.ImageField(label="تصویر اول", widget=forms.FileInput(attrs={'class': 'form-control'}))
    image2 = forms.ImageField(label="تصویر دوم", widget=forms.FileInput(attrs={'class': 'form-control'}))
    class Meta:
        model = Post
        fields = ['title', 'description', 'reading_time', 'category']
        widgets={
            'title': forms.TextInput(attrs={
                'class':'form-control',
                'id' : "con-name",

            }),
            'description': forms.Textarea(attrs={
            	'class': 'form-control',
				 'rows': '5',
            }),
            'reading_time': forms.NumberInput(attrs={
                'class': 'form-control',
            }),
            'category': forms.Select(attrs={
                'class': 'form-select',
            }),


        }


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=250, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(max_length=250, required=True, widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(max_length=20, widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='پسورد')
    password2 = forms.CharField(max_length=20, widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='تکرار پسورد')
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name' , 'email']
        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'form-control',

            }),
            'first_name': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'last_name': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
            }),
        }
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('پسورد ها مطابقت ندارند!')
        return cd['password2']

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']
        widgets = {
            'first_name': forms.TextInput(attrs={
                'class': 'form-control',

            }),
            'last_name': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
            }),
        }

class AccountEditForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['date_of_birth', 'bio', 'job', 'photo']
        widgets = {
            'date_of_birth': forms.DateInput(attrs={
                'class': 'form-control',
            }),
            'bio': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': '5',
            }),
            'job': forms.TextInput(attrs={
                'class': 'form-control',

            }),
            'photo': forms.FileInput(attrs={
                'class': 'form-control',
            }),
        }

blog/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from .models import *
from .forms import *
# from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView
from django.views.decorators.http import require_POST
from django.db.models import Q
from django.contrib.postgres.search import TrigramSimilarity
from django.contrib.auth import authenticate, login, logout
# Create your views here.
from django.contrib.auth.decorators import login_required

def index(request):
    last_post = Post.published.all().order_by('-publish')[0]
    return render(request, "blog/index.html", {"last_post": last_post})


def post_list(request, category=None):
    if category is not None:
        posts = Post.published.filter(category=category)
    else:
        posts = Post.published.all()
    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)
    print(posts, type(posts))
    context = {
        'posts': posts,
        'category': category
    }
    return render(request, "blog/list.html", context)

# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = "posts"
#     paginate_by = 4f
#     template_name = "blog/list.html"


def post_detail(request, pk):
    post = get_object_or_404(Post, id=pk, status=Post.Status.PUBLISHED)
    comments = post.comments.filter(active=True)
    form = CommentForm()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, "blog/detail.html", context)


# class PostDetailView(DetailView):
#     model = Post
#     template_name = "blog/detail.html"


def ticket(request):
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            Ticket.objects.create(message=cd['message'], name=cd['name'], email=cd['email'],
                                  phone=cd['phone'], subject=cd['subject'])
            return redirect("blog:index")
    else:
        form = TicketForm()
    return render(request, "forms/ticket.html", {'form': form})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    context = {
        'post': post,
        'form': form,
        'comment': comment
    }
    return render(request, "forms/comment.html", context)


def post_search(request):
    query=None
    results=[]
    if 'query' in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query=form.cleaned_data['query']
            results1=Post.published.annotate(similarity=TrigramSimilarity('title', query))\
                .filter(similarity__gt=0.1)
            results2 = Post.published.annotate(similarity=TrigramSimilarity('description', query)) \
                .filter(similarity__gt=0.1)
            results = (results1 | results2).order_by('-similarity')
    context={
        'query':query,
        'results':results
    }
    return render(request,'blog/search.html',context)

@login_required
def profile(request):
    user = request.user
    posts= Post.published.filter(author=user)

    return render(request, 'blog/profile.html', {'posts':posts})

@login_required
def create_post(request):
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_file=form.cleaned_data['image1'], post= post)
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            return redirect('blog:profile')
    else:
        form = CreatePostForm()
    return render(request, 'forms/create-post.html', {'form': form})

@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        post.delete()
        return redirect('blog:profile')
    return render(request, 'forms/delete-post.html', {'post': post})

@login_required
def delete_image(request, image_id):
    image = get_object_or_404(Image, id=image_id)
    image.delete()
    return redirect('blog:profile')

@login_required
def edit_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_file=form.cleaned_data['image1'], post=post)
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            return redirect('blog:profile')
    else:
        form = CreatePostForm(instance=post)
    return render(request, 'forms/create-post.html', {'form': form, 'post': post})

# def user_login(request):
#     if request.method == "POST":
#         form = LoginForm(request.POST)
#         if form.is_valid():
#             cd = form.cleaned_data
#             user = authenticate(request, username=cd['username'], password=cd['password'])
#             if user is not None:
#                 if user.is_active:
#                     login(request, user)
#                     return redirect('blog:profile')
#                 else:
#                     return HttpResponse('Your account is disabled')
#             else:
#                 return HttpResponse('You are not logged in')
#
#     else:
#         form = LoginForm()
#     return render(request, 'forms/login.html', {'form': form})

def log_out(request):
    logout(request)
    return redirect(request.META.get('HTTP_REFERER'))


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            Account.objects.create(user=user)
            return  render(request, 'registration/register_done.html', {'user': user})
    else:
        form = UserRegisterForm()
    return render(request, 'registration/register.html', {'form': form})


@login_required
def edit_account(request):
    if request.method == 'POST':
        user_form = UserEditForm(request.POST, instance=request.user)
        account_form = AccountEditForm(request.POST, instance=request.user.account, files=request.FILES)
        if account_form.is_valid() and user_form.is_valid():
            account_form.save()
            user_form.save()
    else:
        user_form = UserEditForm(instance=request.user)
        account_form = AccountEditForm(instance=request.user.account)
    context ={
        'account_form': account_form,
        'user_form': user_form
    }
    return render(request, 'registration/edit_account.html', context)

blog/templates/blog/detail.html
{% extends 'parent/base.html' %}
{% block title %}post list{% endblock %}
{% load static %}
{% load blog_tags %}
{% load jformat %}
{% block head %} {% endblock %}

{% block content %}


<body>
<!-- Preloader START -->
	<div class="preloader">
		<div class="loader">
			<div class="sh1"></div>
			<div class="sh2"></div>
		</div>
	</div>
<!-- Preloader END -->

<main>

<!-- =======================
Inner intro START -->
<section class="pt-2">
	<div class="container">
		<div class="row">
      <div class="col-12">
        <div class="card bg-dark-overlay-5 overflow-hidden card-bg-scale h-400 text-center" style="background-image:url({{ post.images.first.image_file.url }}); background-position: center left; background-size: cover;">
          <!-- Card Image overlay -->
          <div class="card-img-overlay d-flex align-items-center p-3 p-sm-4">
            <div class="w-100 my-auto">
              <!-- Card category -->
              <a href="#" class="badge text-bg-danger mb-2"><i class="fas fa-circle me-2 small fw-bold"></i>{{ post.category }}</a>
              <!-- Card title -->
              <h2 class="text-white display-5">{{ post.title}}</h2>
              <!-- Card info -->
              <ul class="nav nav-divider text-white-force align-items-center justify-content-center">
                <li class="nav-item">
                  <div class="nav-link">
                    <div class="d-flex align-items-center text-white position-relative">
                      <div class="avatar avatar-sm">
                        <img class="avatar-img rounded-circle" src="{{post.author.account.photo.url}}" alt="avatar">
                      </div>
                      <span class="ms-3">با <a href="#" class="stretched-link text-reset btn-link">{{ post.author }}</a></span>
                    </div>
                  </div>
                </li>
                <li class="nav-item">{{ post.publish|jformat:"%Y/%m/%d-%H:%M" }}</li>
                <li class="nav-item">{{post.reading_time}} دقیقه </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
	</div>
</section>
<!-- =======================
Inner intro END -->

<!-- =======================
Main START -->
<section class="pt-0">
	<div class="container position-relative" data-sticky-container>
		<div class="row">
			<!-- Main Content START -->
			<div class="col-lg-9 mb-5">
      	<p><span class="dropcap bg-dark text-white px-2">I</span>{{ post.description | markdown  }}</p>

				<!-- Images -->
				<div class="row g-2 my-5">
					{% for img in post.images.all %}
					<div class="col-md-4">
						<a href="{{ img.image_file.url }}" data-glightbox data-gallery="image-popup">
			      	<img class="rounded" src="{{ img.image_file.url }}" alt="{{ img.title }}">
			       </a>
					</div>
					{%endfor %}
				</div>

				<!-- Divider -->
				<div class="text-center h5 mb-4">. . .</div>

				<!-- Author info START -->
				<div class="d-flex p-2 p-md-4 my-3 bg-primary bg-opacity-10 rounded">
					<!-- Avatar -->
					<a href="#">
						<div class="avatar avatar-xxl me-2 me-md-4">
							<img class="avatar-img rounded-circle" src="{{post.author.account.photo.url}}" alt="avatar">
						</div>
					</a>
					<!-- Info -->
					<div>
						<div class="d-sm-flex align-items-center justify-content-between">
							<div>
					<h4 class="m-0"><a href="#" class="text-reset">{{ post.author }}</a></h4>
								<small>{{ post.author.account.job}}</small>
							</div>
						</div>
						<p class="my-2">{{ post.author.account.bio }}</p>
					</div>
				</div>
				<!-- Author info END -->

				<!-- Comments START -->
				<div class="mt-5">
					{% with comments.count as cm_count%}
					<h3> {{ cm_count }} دیدگاه </h3>
                	{% endwith %}
					<!-- Comment level 1-->
					{% for cm in comments %}
					<div class="my-4 d-flex">
					  <img class="avatar avatar-md rounded-circle float-start me-3" src="{% static 'images/avatar/av1.png' %}" alt="avatar">
					  <div>
					    <div class="mb-2">
					    	<h5 class="m-0">{{ cm.name }}</h5>
					    	<span class="me-3 small">{{ post.created|jformat:"%Y/%m/%d-%H:%M" }} </span>
					    </div>
					    <p>{{ cm.body|linebreaks}}</p>
					  </div>
					</div>
					{% empty %}
					<p>کامنتی وجود ندارد!</p>
					 {% endfor %}
				</div>
				<!-- Comments END -->


				<!-- Reply START -->
				<div>
					<h3>ثبت دیدگاه</h3>
					<small>آدرس ایمیل شما منتشر نخواهد شد.</small>
					<form class="row g-3 mt-2" method="post" action="{% url 'blog:post_comment' post.id %}" >
						{% csrf_token %}
						{{ form.as_div }}
					  <div class="col-12">
					    <button type="submit" class="btn btn-primary">ثبت</button>
					  </div>
					</form>
				</div>
				<!-- Reply END -->
			</div>
			<!-- Main Content END -->

			<!-- Right sidebar START -->
			<div class="col-lg-3">
				<div data-sticky data-margin-top="80" data-sticky-for="991">
          <!-- Categories -->
	      	<div class="row g-2">
						<h5>دسته بندی ها</h5>
						<div class="d-flex justify-content-between align-items-center bg-warning bg-opacity-15 rounded p-2 position-relative">
							<h6 class="m-0 text-warning"><a href="{% url 'blog:post_list_category' 'تکنولوژی' %}">تکنولوژی</a></h6>
						</div>
						<div class="d-flex justify-content-between align-items-center bg-info bg-opacity-10 rounded p-2 position-relative">
							<h6 class="m-0 text-info"><a href="{% url 'blog:post_list_category' 'زبان برنامه نویسی' %}">زبان برنامه نویسی</a></h6>
						</div>
						<div class="d-flex justify-content-between align-items-center bg-danger bg-opacity-10 rounded p-2 position-relative">
							<h6 class="m-0 text-danger"><a href="{% url 'blog:post_list_category' 'هوش مصنوعی' %}">هوش مصنوعی</a></h6>
						</div>
						<div class="d-flex justify-content-between align-items-center bg-primary bg-opacity-10 rounded p-2 position-relative">
							<h6 class="m-0 text-primary"><a href="{% url 'blog:post_list_category' 'بلاکچین' %}">بلاکچین</a></h6>
						</div>
						<div class="d-flex justify-content-between align-items-center bg-success bg-opacity-10 rounded p-2 position-relative">
							<h6 class="m-0 text-success"><a href="{% url 'blog:post_list_category' 'سایر' %}">سایر</a></h6>
						</div>
					</div>


					<div class="mt-4">
						<a href="#" class="d-block card-img-flash">
							<img src="assets/images/adv.png" alt="">
						</a>
					</div>
				</div>
			</div>
			<!-- Right sidebar END -->
		</div>
	</div>
</section>
<!-- =======================
Main END -->

<!-- =======================
Sticky post START -->

<!-- =======================
Sticky post END -->

</main>
<!-- **************** MAIN CONTENT END **************** -->

<!-- Back to top -->
<div class="back-top"><i class="bi bi-arrow-up-short"></i></div>

<!-- =======================
JS libraries, plugins and custom scripts -->

<!-- Bootstrap JS -->
<script src="{% static 'vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>

<!-- Vendors -->
<script src="{% static 'vendor/sticky-js/sticky.min.js' %}"></script>
<script src="{% static 'vendor/glightbox/js/glightbox.js' %}"></script>

<!-- Template Functions -->
<script src="{% static 'js/functions.js' %}"></script>

{% endblock %}

blog/templates/blog/profile.html
{% extends 'parent/base.html' %}
{% block title %}profile{% endblock %}
{% load static %}
{% load blog_tags %}
{% load jformat %}
{% block head %} {% endblock %}

{% block content %}

<!-- Preloader START -->
	<div class="preloader">
		<div class="loader">
			<div class="sh1"></div>
			<div class="sh2"></div>
		</div>
	</div>
<!-- Preloader END -->

<section class="py-4">
	<div class="container">
    <div class="row pb-4">
			<div class="col-12">
        <!-- Title -->
				<div class="d-sm-flex justify-content-sm-between align-items-center">
					<h1 class="mb-2 mb-sm-0 h3">منوی کاربری</h1>
					<a href="{% url 'blog:create_post' %}" class="btn btn-sm btn-primary mb-0"><i class="fas fa-plus me-2"></i>ایجاد پست جدید</a>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-12">

          <div class="row g-4 mb-4">
            <div class="col-sm-4 col-lg-2">
              <!-- Card START -->
              <div class="card card-body border h-120">
                <!-- Icon -->
                <div class="fs-5 text-start text-success">
                  <a class="dropdown-item" href="{% url 'blog:password_change' %}"><i class="bi bi-pen fa-fw me-2"></i>تغییر پسورد</a>
                </div>
                <!-- Content -->
              </div>
              <!-- Card END -->
            </div>

               <div class="col-sm-4 col-lg-3">
              <!-- Card START -->
              <div class="card card-body border h-120">
                <!-- Icon -->
                <div class="fs-5 text-start text-success">
                  <a class="dropdown-item" href="{% url 'blog:edit_account' %}"><i class="bi bi-pencil fa-fw me-2"></i>تغییر اطلاعات شخصی</a>
                </div>
                <!-- Content -->
              </div>
              <!-- Card END -->
            </div>


                          <div class="col-sm-4 col-lg-2">
              <!-- Card START -->
              <div class="card card-body border h-120">
                <!-- Icon -->
                <div class="fs-5 text-start text-success">
                  <a class="dropdown-item" href="{% url 'blog:logout' %}"><i class="bi bi-power fa-fw me-2"></i>خروج</a>
                </div>
                <!-- Content -->
              </div>
              <!-- Card END -->
            </div>

                             <div class="col-sm-4 col-lg-2">
              <!-- Card START -->
              <div class="card card-body border h-120">
                <!-- Icon -->
                <div class="fs-5 text-start text-success">
                  <a class="dropdown-item" href="{% url 'blog:ticket' %}"><i class="bi bi-messenger fa-fw me-2"></i>ارسال تیکت</a>
                </div>
                <!-- Content -->
              </div>
              <!-- Card END -->
            </div>


            </div>
          </div>
          <!-- Post list table START -->
          <div class="card border bg-transparent rounded-3">

              <!-- Post list table START -->
              <div class="table-responsive border-0">
                <table class="table align-middle p-4 mb-0 table-hover table-shrink">
                  <!-- Table head -->
                  <thead class="table-dark">
                    <tr>
                      <th scope="col" class="border-0">ردیف</th>
                      <th scope="col" class="border-0">عنوان</th>
                      <th scope="col" class="border-0">تاریخ انتشار</th>
                      <th scope="col" class="border-0">وضعیت</th>
                      <th scope="col" class="border-0 rounded-end">عملیات</th>
                    </tr>
                  </thead>

                  <!-- Table body START -->
                  <tbody class="border-top-0">
                    <!-- Table item -->
                    {% for post in posts %}
                    <tr>
                      <!-- Table data -->
                      <td>
                        <h6 class="course-title mt-2 mt-md-0 mb-0"><a href="#">{{ forloop.counter}}</a></h6>
                      </td>
                       <!-- Table data -->
                      <td>
                        <a href="{{ post.get_absolute_url }}" class="badge text-bg-success mb-2">{{ post.title }}</a>
                      </td>
                      <!-- Table data -->
                      <td>{{ post.publish|jformat:"%Y/%m/%d-%H:%M" }}</td>

                      <!-- Table data -->
                      <td>
                        <span class="badge bg-warning bg-opacity-15 text-warning mb-2">{{ post.status}}</span>
                      </td>
                      <!-- Table data -->
                      <td>
                        <div class="d-flex gap-2">
                          <a href="{% url 'blog:delete_post' post.id %}" class="btn btn-light btn-round mb-0" data-bs-toggle="tooltip" data-bs-placement="top" title="حذف"><i class="bi bi-trash"></i></a>
                          <a href="{% url 'blog:edit_post' post.id%}" class="btn btn-light btn-round mb-0" data-bs-toggle="tooltip" data-bs-placement="top" title="ویرایش"><i class="bi bi-pencil-square"></i></a>
                        </div>
                      </td>
                    </tr>
                  {% endfor %}
                  </tbody>
                  <!-- Table body END -->
                </table>
              </div>
              <!-- Post list table END -->
            </div>
          </div>
          <!-- Post list table END -->
      </div>
    </div>
  </div>
</section>
<!-- =======================
Main contain END -->

</main>
<!-- **************** MAIN CONTENT END **************** -->

<!-- Back to top -->
<div class="back-top"><i class="bi bi-arrow-up-short"></i></div>
<!-- =======================
JS libraries, plugins and custom scripts -->

<!-- Bootstrap JS -->
<script src="{% static 'vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>

<!-- Vendors -->
<script src="{% static 'vendor/apexcharts/js/apexcharts.min.js' %}"></script>
<script src="{% static 'vendor/quill/js/quill.min.js' %}"></script>

<!-- Template Functions -->
<script src="{% static 'js/functions.js' %}"></script>


{% endblock %}

blog/templates/blog/search.html
{% extends 'parent/base.html' %}
{% block title %}post search{% endblock %}
{% load static %}
{% load blog_tags %}
{% block content %}
    {% if query %}
      <div class="mb-4 text-center">
        <h2 class="h1 m-0"> نتایج جستجو برای {{ query }}</h2>
        <h2 class="h2 m-0">{{ results.count }} نتیجه </h2>
      </div>
    {% endif %}
    <br>
    {% for post in results %}
<div class="container" data-sticky-container>
    <div class="card mb-4">
        <div class="row">
            <div class="col-md-7 mt-3 mt-md-0">
                <h4><a href="{{post.get_absolute_url}}" class="btn-link stretched-link text-reset"><i class="fas fa-circle me-2 small fw-bold"></i>{{ post.title}}</a></h4>
                <p>{{ post.description | markdown | truncatewords:20 }} </p>
            </div>
        </div>
    </div>
</div>
    {% empty %}
        <p>هیچ نتیجه ای یافت نشد </p>
    {% endfor %}

    <!-- Bootstrap JS -->
<script src="{% static 'vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>

<!-- Template Functions -->
<script src="{% static 'js/functions.js' %}"></script>

{% endblock %}